version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@1.0.0
commands:
  sync_to_s3:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync: # Invoke the sync command declared in the s3 orb
          arguments: --cache-control "max-age=604800"
          from: /tmp/workspace/dist
          to: $AWS_S3_SYNC_TO # Read the S3 URL from the CircleCI context
          overwrite: true
jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx semantic-release
            - store_artifacts:
                path: package.json
            - persist_to_workspace:
                root: ~/project
                paths:
                  - package.json
  build:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: /tmp/workspace
            # If the release job was run, overwrite the package.json with the one that was persisted in the workspace
            - run: "cp /tmp/workspace/package.json ~/project/package.json 2>/dev/null || :"
            - run: npm install
            - run: npm run build
            - persist_to_workspace:
                root: ~/project
                paths:
                  - dist
                  - cloudformation
  deploy-cloudformation-stack:
    executor: aws-cli/default
    parameters:
      stack_name:
        type: string
      domain:
        type: string
      aliases:
        type: string
      ssl_certificate_arn:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/setup
      - run: >
          aws cloudformation deploy 
          --stack-name=<< parameters.stack_name >> 
          --template-file=/tmp/workspace/cloudformation/keinecookies.template 
          --no-fail-on-empty-changeset 
          --parameter-overrides 
          HostedZone=keinecookies.de 
          Domain=<< parameters.domain >> 
          Aliases=<< parameters.aliases >> 
          SslCertificateArn=<< parameters.ssl_certificate_arn >>           
  deploy-website-to-s3:
    docker:
      - image: cimg/python:3.6
    steps:
      - sync_to_s3
workflows:
  build-and-deploy:
    jobs:
      - build:
          name: build-dev
          filters:
            branches:
              ignore: 
                - master
      - release:
          filters:
            branches:
              only: 
                - master
      - build:
          name: build-prod
          requires:
            - release
          filters:
            branches:
              only: 
                - master
      - deploy-cloudformation-stack:
          name: deploy-cloudformation-stack-dev
          stack_name: dev
          domain: dev.keinecookies.de
          aliases: dev.keinecookies.de
          ssl_certificate_arn: arn:aws:acm:us-east-1:452562348886:certificate/4c4d019e-6e9b-4dcb-a1a0-80ae2b425dd2
          requires:
            - build-dev
          filters:
            branches:
              only: 
                - develop
      - deploy-cloudformation-stack:
          name: deploy-cloudformation-stack-prod
          stack_name: prod
          domain: keinecookies.de
          aliases: keinecookies.de,www.keinecookies.de
          ssl_certificate_arn: arn:aws:acm:us-east-1:452562348886:certificate/b49e5386-f97d-4b92-babe-f4b2b6df9cb4
          requires:
            - build-prod
          filters:
            branches:
              only: 
                - master
      - deploy-website-to-s3:
          name: deploy-website-to-s3-dev
          context: develop
          requires:
            - deploy-cloudformation-stack-dev
          filters:
            branches:
              only: 
                - develop
      - deploy-website-to-s3:
          name: deploy-website-to-s3-prod
          context: master
          requires:
            - deploy-cloudformation-stack-prod
          filters:
            branches:
              only: 
                - master
