version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
  aws-cli: circleci/aws-cli@1.0.0
commands:
  sync_to_s3:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync: # Invoke the sync command declared in the s3 orb
          arguments: --cache-control "max-age=604800"
          from: /tmp/workspace/dist
          to: $AWS_S3_SYNC_TO # Read the S3 URL from the CircleCI context
          overwrite: true
  update_cloudformation_stack:
    parameters:
      stack_name:
        type: string
      domain:
        type: string
      ssl_certificate_arn:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/setup
      - run: >
          aws cloudformation deploy 
          --stack-name=<< parameters.stack_name >> 
          --template-file=/tmp/workspace/cloudformation/keinecookies.template 
          --no-fail-on-empty-changeset 
          --parameter-overrides 
          HostedZone=keinecookies.de 
          Domain=<< parameters.domain >> 
          SslCertificateArn=<< parameters.ssl_certificate_arn >> 
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - persist_to_workspace:
                root: ~/project
                paths:
                  - dist
                  - cloudformation
  update-cloudformation-stack-dev:
    executor: aws-cli/default
    steps:
      - update_cloudformation_stack:
          stack_name: dev
          domain: dev.keinecookies.de
          ssl_certificate_arn: arn:aws:acm:us-east-1:452562348886:certificate/4c4d019e-6e9b-4dcb-a1a0-80ae2b425dd2
  deploy-to-dev:
    docker:
      - image: cimg/python:3.6
    steps:
      - sync_to_s3
  deploy-to-prod:
    docker:
      - image: cimg/python:3.6
    steps:
      - sync_to_s3
workflows:
  build-and-deploy:
    jobs:
      - build
      - update-cloudformation-stack-dev:
          requires:
            - build
          filters:
            branches:
              only: 
                - develop
      - deploy-to-dev:
          context: develop
          requires:
            - update-cloudformation-stack-dev
          filters:
            branches:
              only: 
                - develop
      - deploy-to-prod:
          context: master
          requires:
            - build
          filters:
            branches:
              only: 
                - master
