version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - persist_to_workspace:
                root: ~/project
                paths:
                  - dist
  deploy:
    docker:
      - image: cimg/python:3.6
    parameters:
      sync_to:
        description: "The S3 URL to sync to"
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync: # Invoke the sync command declared in the s3 orb
          arguments: --cache-control "max-age=604800"
          from: /tmp/workspace/dist
          to: "<< parameters.sync_to >>"
          overwrite: true
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # Only run deploy job once the build job has completed
          filters:
            branches:
              only: 
                - master
                - develop
          sync_to: ${CIRCLE_BRANCH}


