version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
  cloudformation: davidkelley/cloudformation@1.2.3
commands:
  sync_to_s3:
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync: # Invoke the sync command declared in the s3 orb
          arguments: --cache-control "max-age=604800"
          from: /tmp/workspace/dist
          to: $AWS_S3_SYNC_TO # Read the S3 URL from the CircleCI context
          overwrite: true
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - persist_to_workspace:
                root: ~/project
                paths:
                  - dist
  deploy-to-dev:
    docker:
      - image: cimg/python:3.6
    steps:
      - sync_to_s3
  deploy-to-prod:
    docker:
      - image: cimg/python:3.6
    steps:
      - sync_to_s3
workflows:
  build-and-deploy:
    jobs:
      - build
      - cloudformation/deploy:
          stack-name: dev
          workspace: /tmp/workspace
          template-file: cloudformation/keinecookies.template
          input-json: /tmp/workspace/cloudformation/env-dev.json
          output-json: /tmp/workspace/output.json
          after-deploy:
            - run:
                command: |
                  cat /workspace/outputs.json | jq
          requires:
            - build
          filters:
            branches:
              only: 
                - develop
      - deploy-to-dev:
          context: develop
          requires:
            - cloudformation/deploy
          filters:
            branches:
              only: 
                - develop
      - deploy-to-prod:
          context: master
          requires:
            - build
          filters:
            branches:
              only: 
                - master
